export default [
  {
    id: 0,
    img: "/jacket.jpg",
    name: "MEN Yarn Fleece Full-Zip Jacket",
    price: 45.00,
    category: ["men's"],
    sale: false,
  },
  {
    id: 1,
    img: "/skirt.jpg",
    name: "White Floral Wrap Midi Skirt",
    price: 55.00,
    category: ["women's"],
    sale: false,
  },
  {
    id: 2,
    img: "/smart-watch.jpg",
    name: "Smart Watches Vital Plus",
    price: 100.00,
    category: ["jewelry", "men's"],
    sale: false,
  },
  {
    id: 3,
    img: "/shirt.jpg",
    name: "Pure Garment Dyed Cotton T-Shirt",
    price: 45.00,
    category: ["men's"],
    sale: true,
  },
  {
    id: 4,
    img: "/shoes.jpg",
    name: "Trekking & Running Shoes - Black",
    price: 58.00,
    category: ["men's"],
    sale: false,
  },
  {
    id: 5,
    img: "/party-wear.jpg",
    name: "Women's Party Wear Dress",
    price: 25.00,
    category: ["women's"],
    sale: true,
  },
  {
    id: 6,
    img: "/pocket-watch.jpg",
    name: "Pocket Watch Leather Pouch",
    price: 120.00,
    category: ["jewelry"],
    sale: false,
  },
  {
    id: 7,
    img: "/lipstick.jpg",
    name: "NYX Matte Lipstick",
    price: 30.00,
    category: ["cosmetics", "women's"],
    sale: true,
  },
];
